### ISSUE TITLE
Pretraining Problem

### ISSUE THREAD

**Issue by bennigeir** [studio-ousia/luke#109]
Hi,

Thank you for making your code available!

I'm currently trying to reproduce the pretraining of LUKE using the English version of wikipedia.
I'm following the steps provided in [issue 41](https://github.com/studio-ousia/luke/issues/41).

> It seems the steps to pretrain is fairly trivial. You can execute `python -m luke.cli` and follows all listed command step by step and it should be fine
> 
> 1. Parse wikipedia dump to database
> 
> ```bash
> python -m luke.cli build-dump-db enwiki-latest-pages-articles.xml.bz2 ./enwiki_latest
> ```
> 
> 2. Generate list of entity vocab from your parsed database, you can refer to utils/ent_vocab.py for the additional parameters (size of vocab, white list etc). 
> 
> ```bash
> python -m luke.cli build-entity-vocab  ./enwiki_latest ./output_ent-vocab.jsonl
> ```
> 
> 3. Build your training datasets and metadata needed for pretraining
> 
> do note that I am using roberta-base tokenizer as my tokenizer you can use others such as bert-base-cased etc.
> 
> ```bash
> python -m luke.cli build-wikipedia-pretraining-dataset ./enwiki_latest roberta-base ./output_ent-vocab.jsonl  ./wikipedia_pretrain_dataset
> 
> ```
> 
> 4. Finally you can start your pretraining by running the following command
> 
> ```bash
> python -m luke.cli pretrain \
>     ./wikipedia_pretrain_dataset \
>     luke-roberta-base \
>     --bert-model-name roberta-base \
>     --entity-emb-size 300 \
>     --batch-size 28 \
>     --gradient-accumulation-steps 1 \
>     --learning-rate 0.0005 \
>     --warmup-steps 10000 \
>     --log-dir logs/luke-roberta-base
> ```
> 
> _Originally posted by @theblackcat102 in https://github.com/studio-ousia/luke/issues/41#issuecomment-811580632_

When doing so I encounter an error during step 3:
```python
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\benediktgj\anaconda3\envs\tf\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\benediktgj\anaconda3\envs\tf\lib\multiprocessing\spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input
Traceback (most recent call last):
  File "C:\Users\benediktgj\anaconda3\envs\tf\lib\runpy.py", line 193, in _run_module_as_main
    "_main_", mod_spec)
  File "C:\Users\benediktgj\anaconda3\envs\tf\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\benediktgj\Documents\GitHub\luke\luke\cli.py", line 67, in <module>
    cli()
  File "C:\Users\benediktgj\anaconda3\envs\tf\lib\site-packages\click\core.py", line 1137, in _call_
    return self.main(*args, **kwargs)
  File "C:\Users\benediktgj\anaconda3\envs\tf\lib\site-packages\click\core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "C:\Users\benediktgj\anaconda3\envs\tf\lib\site-packages\click\core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\benediktgj\anaconda3\envs\tf\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\benediktgj\anaconda3\envs\tf\lib\site-packages\click\core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\benediktgj\Documents\GitHub\luke\luke\pretraining\dataset.py", line 57, in build_wikipedia_pretraining_dataset
    WikipediaPretrainingDataset.build(dump_db, tokenizer, sentence_tokenizer, entity_vocab, output_dir, **kwargs)
  File "C:\Users\benediktgj\Documents\GitHub\luke\luke\pretraining\dataset.py", line 193, in build
    Pool(pool_size, initializer=WikipediaPretrainingDataset._initialize_worker, initargs=initargs)
  File "C:\Users\benediktgj\anaconda3\envs\tf\lib\multiprocessing\pool.py", line 176, in _init_
    self._repopulate_pool()
  File "C:\Users\benediktgj\anaconda3\envs\tf\lib\multiprocessing\pool.py", line 241, in _repopulate_pool
    w.start()
  File "C:\Users\benediktgj\anaconda3\envs\tf\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "C:\Users\benediktgj\anaconda3\envs\tf\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Users\benediktgj\anaconda3\envs\tf\lib\multiprocessing\popen_spawn_win32.py", line 89, in _init_
    reduction.dump(process_obj, to_child)
  File "C:\Users\benediktgj\anaconda3\envs\tf\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: can't pickle icu.Locale objects
```

Has anyone encountered this error before, or can anyone help me with this error?

Kind regards,
Benedikt

**Comment by lshowway** [comment]
@ikuyamada I have the same problem now

**Comment by ikuyamada** [comment]
We confirmed that the command can be executed on Linux without issues, so this problem may happen only on Windows. The problem here is that [`ICUSentenceTokenizer`](https://github.com/studio-ousia/luke/blob/master/luke/utils/sentence_tokenizer.py#L20) cannot be pickled, which is required when using the class with multiprocessing. I think it can be possibly solved by changing the code as follows:

```
class ICUSentenceTokenizer:
    """ Segment text to sentences. """

    def __init__(self, locale="en"):
        self.locale = None
        self.breaker = None

    def span_tokenize(self, text: str):
        from icu import Locale, BreakIterator

        if self.breaker is None:
            if locale in {"en", "de", "es", "it", "pt"}:
                locale += "@ss=standard"
            self.locale = Locale(locale)
            self.breaker = BreakIterator.createSentenceInstance(self.locale)

        text = "".join(c if c <= "\uFFFF" else " " for c in text)
        ...
```

**Comment by bennigeir** [comment]
Thank you @ikuyamada for your answer. This code change seems to work on Windows.
I'll be moving my work over to a Linux machine.

**Comment by lshowway** [comment]
Why the entity vocab size is set to 1 million?
