### ISSUE TITLE
Pretraining Problem

### ISSUE THREAD

**Issue by khairunnisaor** [studio-ousia/luke#32]
Hi @ikuyamada,

Thanks for your amazing work about this entity-aware language model. I am interested to build a LUKE model for the Indonesian language. Since I couldn't find any documentation about how to train the model, I did the following steps:
1. Build the dump DB (build-dump-db)
2. Build the entity vocab (build-entity-vocab)
3. Build Wiki pretraining dataset (build-wikipedia-pretraining-dataset)
4. Do the pretraining

However, when starting to do the pretraining, I got some errors:
```
Traceback (most recent call last):
  File "/usr/playground/luke/luke/pretraining/train.py", line 353, in run_pretraining
    result = model(**batch)
  File "/usr/.pyenv/versions/luke/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/playground/luke/luke/pretraining/model.py", line 81, in forward
    entity_attention_mask,
  File "/usr/playground/luke/luke/model.py", line 109, in forward
    entity_embedding_output = self.entity_embeddings(entity_ids, entity_position_ids, entity_segment_ids)
  File "/usr/.pyenv/versions/luke/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/playground/luke/luke/model.py", line 60, in forward
    entity_embeddings = self.entity_embedding_dense(entity_embeddings)
  File "/usr/.pyenv/versions/luke/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/.pyenv/versions/luke/lib/python3.7/site-packages/torch/nn/modules/linear.py", line 87, in forward
    return F.linear(input, self.weight, self.bias)
  File "/usr/.pyenv/versions/luke/lib/python3.7/site-packages/torch/nn/functional.py", line 1612, in linear
    output = input.matmul(weight.t())
RuntimeError: CUDA error: CUBLAS_STATUS_ALLOC_FAILED when calling `cublasCreate(handle)`
[2020-12-09 00:43:15,490] [ERROR] Consecutive errors have been observed. Exiting... (run_pretraining@train.py:379)
Traceback (most recent call last):
  File "/usr/playground/luke/luke/pretraining/train.py", line 352, in run_pretraining
    batch = {k: torch.from_numpy(v).to(device) for k, v in batch.items()}
  File "/usr/playground/luke/luke/pretraining/train.py", line 352, in <dictcomp>
    batch = {k: torch.from_numpy(v).to(device) for k, v in batch.items()}
RuntimeError: CUDA error: an illegal memory access was encountered
Traceback (most recent call last):
  File "./luke/cli.py", line 67, in <module>
    cli()
  File "/usr/.pyenv/versions/luke/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/.pyenv/versions/luke/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/.pyenv/versions/luke/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/.pyenv/versions/luke/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/.pyenv/versions/luke/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/playground/luke/luke/pretraining/train.py", line 82, in pretrain
    run_pretraining(Namespace(**kwargs))
  File "/usr/playground/luke/luke/pretraining/train.py", line 352, in run_pretraining
    batch = {k: torch.from_numpy(v).to(device) for k, v in batch.items()}
  File "/usr/playground/luke/luke/pretraining/train.py", line 352, in <dictcomp>
    batch = {k: torch.from_numpy(v).to(device) for k, v in batch.items()}
RuntimeError: CUDA error: an illegal memory access was encountered
```

Meanwhile, when trying to run the code in cpu, I got this error:
```IndexError: index out of range in self```

Is it a cuda error or maybe because of the tensors? 

Thank you in advance for your help!

Best,
Oryza

**Comment by ikuyamada** [comment]
Hi @khairunnisaor,

Thank you very much for using LUKE.
I am sorry but there is no documentation for pretraining of LUKE.

Would you provide the stacktrace when running pretraining on CPU?

Thanks,
Ikuya

**Comment by khairunnisaor** [comment]
Hi @ikuyamada,

Thanks for your fast response. Yes it's totally okay, your code is easy to understand actually so thanks for that, but maybe I will ask you some stuff if I don't understand hehe.

I run this command 
```python ./luke/cli.py pretrain idwiki-dataset idluke-pretrain-robertalarge --cpu --log-dir idluke-pretrain-robertalarge-log```

and got this error;
```
Traceback (most recent call last):
  File "./luke/cli.py", line 67, in <module>
    cli()
  File "/usr/.pyenv/versions/luke/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/.pyenv/versions/luke/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/.pyenv/versions/luke/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/.pyenv/versions/luke/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/.pyenv/versions/luke/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/playground/luke/luke/pretraining/train.py", line 82, in pretrain
    run_pretraining(Namespace(**kwargs))
  File "/usr/playground/luke/luke/pretraining/train.py", line 353, in run_pretraining
    result = model(**batch)
  File "/usr/.pyenv/versions/luke/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/playground/luke/luke/pretraining/model.py", line 81, in forward
    entity_attention_mask,
  File "/usr/playground/luke/luke/model.py", line 105, in forward
    embedding_output = self.embeddings(word_ids, word_segment_ids)
  File "/usr/.pyenv/versions/luke/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/.pyenv/versions/luke/lib/python3.7/site-packages/transformers/modeling_roberta.py", line 66, in forward
    input_ids, token_type_ids=token_type_ids, position_ids=position_ids, inputs_embeds=inputs_embeds
  File "/usr/.pyenv/versions/luke/lib/python3.7/site-packages/transformers/modeling_bert.py", line 174, in forward
    inputs_embeds = self.word_embeddings(input_ids)
  File "/usr/.pyenv/versions/luke/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/.pyenv/versions/luke/lib/python3.7/site-packages/torch/nn/modules/sparse.py", line 114, in forward
    self.norm_type, self.scale_grad_by_freq, self.sparse)
  File "/usr/.pyenv/versions/luke/lib/python3.7/site-packages/torch/nn/functional.py", line 1724, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
IndexError: index out of range in self```

Am I using the command correctly?

Thanks,
Oryza

**Comment by ikuyamada** [comment]
It seems that this error is related to the word embeddings. I think the `word_ids` input tensor contains invalid values for some reason.
https://github.com/studio-ousia/luke/blob/master/luke/model.py#L105

**Comment by khairunnisaor** [comment]
Hi @ikuyamada,

thanks for your answer! 
about the `word_ids`, I don't understand how should I set it, it should be created when calling the `LukePretrainingModel` in `train.py`, no?

and in that case, did I do the steps (as I mentioned in my first comment) before using the pretraining command correctly? 

Best,
Oryza

**Comment by khairunnisaor** [comment]
Hi @ikuyamada,

sorry for asking about this again but just to confirm, are these the right steps to do the pre-training? 
1. Build the dump DB (build-dump-db)
2. Build the entity vocab (build-entity-vocab)
3. Build Wiki pretraining dataset (build-wikipedia-pretraining-dataset)
4. Do the pretraining (pretrain)

Thank you in advance!

Best,
Oryza

**Comment by ikuyamada** [comment]
Hi,
I am sorry for the delayed reply. Yes, these steps are correct. Currently, we tested our code only on English, thus there might be some unknown issues when it is applied to other languages.

**Comment by khairunnisaor** [comment]
Hi,

Thank you so much for your prompt reply and confirmation of the steps!

I see, I also think about the language factor. However, actually Indonesian has a very similar grammar and exactly the same alphabet with English. Do you have any thoughts about what factor that affects the data?

Thank you!

Best,
Oryza

**Comment by khairunnisaor** [comment]
Hi, 

I just realized that I used the roberta model as the embeddings. That might be my mistake I guess, I should've used Indonesian BERT instead. I'll let you know if it's working after using the right BERT model. Sorry for my question before.

Best,
Oryza
