### ISSUE TITLE
Memory leak in training?

### ISSUE THREAD

**Issue by Riroaki** [studio-ousia/luke#33]
Hi, thanks for your great work!
I was using LUKE for RC on TACRED dataset, but the training always aborts due to OOM problem during the training process, which is unlikely to happen as the memory should stay the same during the training? Is there any possibility of memory leak?
```
[2020-12-09 15:33:29,940] [INFO] Loading features from cached file data/tacred/cached_roberta_30_train.pkl (load_and_cache_examples@main.py:188)
epoch: 0 loss: 1.7077439:   1%|▉                                                                                        | 1703/170310 [11:36<19:09:14,  2.45it/s]
Traceback (most recent call last):
  File "/home/llq/anaconda3/envs/py36/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/llq/anaconda3/envs/py36/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/llq/homework/luke/examples/cli.py", line 135, in <module>
    cli()
  File "/home/llq/anaconda3/envs/py36/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/llq/anaconda3/envs/py36/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/llq/anaconda3/envs/py36/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/llq/anaconda3/envs/py36/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/llq/anaconda3/envs/py36/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/llq/anaconda3/envs/py36/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/llq/homework/luke/examples/utils/trainer.py", line 32, in wrapper
    return func(*args, **kwargs)
  File "/home/llq/anaconda3/envs/py36/lib/python3.6/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/home/llq/homework/luke/examples/relation_classification/main.py", line 94, in run
    trainer.train()
  File "/home/llq/homework/luke/examples/utils/trainer.py", line 93, in train
    outputs = model(**inputs)
  File "/home/llq/anaconda3/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/llq/homework/luke/examples/relation_classification/model.py", line 38, in forward
    entity_attention_mask,
  File "/home/llq/homework/luke/luke/model.py", line 213, in forward
    return self.encoder(word_embeddings, entity_embeddings, attention_mask)
  File "/home/llq/anaconda3/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/llq/homework/luke/luke/model.py", line 342, in forward
    word_hidden_states, entity_hidden_states, attention_mask
  File "/home/llq/anaconda3/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/llq/homework/luke/luke/model.py", line 325, in forward
    word_hidden_states, entity_hidden_states, attention_mask
  File "/home/llq/anaconda3/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/llq/homework/luke/luke/model.py", line 308, in forward
    word_self_output, entity_self_output = self.self(word_hidden_states, entity_hidden_states, attention_mask)
  File "/home/llq/anaconda3/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/llq/homework/luke/luke/model.py", line 287, in forward
    attention_probs = self.dropout(attention_probs)
  File "/home/llq/anaconda3/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/llq/anaconda3/envs/py36/lib/python3.6/site-packages/torch/nn/modules/dropout.py", line 54, in forward
    return F.dropout(input, self.p, self.training, self.inplace)
  File "/home/llq/anaconda3/envs/py36/lib/python3.6/site-packages/torch/nn/functional.py", line 807, in dropout
    else _VF.dropout(input, p, training))
RuntimeError: CUDA out of memory. Tried to allocate 12.00 MiB (GPU 0; 10.91 GiB total capacity; 8.55 GiB already allocated; 8.50 MiB free; 8.75 GiB reserved in total by PyTorch)
```

**Comment by ikuyamada** [comment]
Hi,
Thank you for using LUKE.

In our current implementation, the length of the input sequence can vary, so OOM error can happen in the middle of the training process.

**Comment by Riroaki** [comment]
Thanks for your instant reply!
So is there any easy way to keep the sequence length fixed?

**Comment by ikuyamada** [comment]
You can fix the length of the input sequences (i.e., word sequence and entity sequence) by modifying here:
https://github.com/studio-ousia/luke/blob/master/examples/relation_classification/main.py#L200
Instead of using `torch.nn.utils.rnn.pad_sequence`, you need to pad the sequence that generates fixed input sequences.

**Comment by Riroaki** [comment]
Thanks, what about modifying the length of features? As the padding process includes changing the length of all features, I suppose changing the length of `tokens` at https://github.com/studio-ousia/luke/blob/9323b216dd5f72b61545bc4133f7709fd19bfa95/examples/relation_classification/utils.py#L137 might work as well? I would simply truncate the token sequence to a fixed length then...

**Comment by ikuyamada** [comment]
Hi, I think that also works!

**Comment by Riroaki** [comment]
Thanks again! BTW what's the usage of cached pickle file? I checked it and found an integer in it.

**Comment by ikuyamada** [comment]
The cache file contains data fed into the model, such as input sequences and labels. The cache file should be removed after modifying the code inside `convert_examples_to_features`.
https://github.com/studio-ousia/luke/blob/master/examples/relation_classification/main.py#L167

**Comment by Riroaki** [comment]
Thanks! I modified it and removed the cache, no problems occurred since then.😄
