### ISSUE TITLE
Running provided RE code returns `RuntimeError: pytorch_model.bin is a zip archive` error

### ISSUE THREAD

**Issue by seanswyi** [studio-ousia/luke#60]
Hi. I downloaded the model and checkpoint you provided and am trying to run relation extraction. Per a previous Issue, I did as you suggested and have managed to set up the packages as you specify.

Specifically, I'm running the command:

```
python -m examples.cli \
--model-file=/hdd1/user/research/luke/luke_large_500k.tar.gz \
--output-dir=/hdd1/user/research/luke \
relation-classification run \
--data-dir=/hdd1/user/data/TACRED/data/json \
 --checkpoint-file=/hdd1/user/research/luke/pytorch_model.bin \
--no-train
```

but this returns a `RuntimeError: /hdd1/user/research/luke/pytorch_model.bin is a zip archive (did you mean to use torch.jit.load()?)`. According to [this PyTorch Discussion Forum answer](https://discuss.pytorch.org/t/problem-with-my-checkpoint-file-when-using-torch-load/92903/2?u=seankala) it seems this may stem from using differing PyTorch version when saving and loading checkpoints? I'm not sure if I can address this issue though. The PyTorch version that I've installed using the `requirements.txt` is 1.2.0.

Would you have any idea what may be causing this issue? Thanks.

---

Here's the entire traceback in case it provides some more info:

```
Traceback (most recent call last):
  File "/home/user/anaconda3/envs/luke/lib/python3.7/tarfile.py", line 187, in nti
    n = int(s.strip() or "0", 8)
ValueError: invalid literal for int() with base 8: 'r_v2\nq\x02('

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/anaconda3/envs/luke/lib/python3.7/tarfile.py", line 2289, in next
    tarinfo = self.tarinfo.fromtarfile(self)
  File "/home/user/anaconda3/envs/luke/lib/python3.7/tarfile.py", line 1095, in fromtarfile
    obj = cls.frombuf(buf, tarfile.encoding, tarfile.errors)
  File "/home/user/anaconda3/envs/luke/lib/python3.7/tarfile.py", line 1037, in frombuf
    chksum = nti(buf[148:156])
  File "/home/user/anaconda3/envs/luke/lib/python3.7/tarfile.py", line 189, in nti
    raise InvalidHeaderError("invalid header")
tarfile.InvalidHeaderError: invalid header

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/anaconda3/envs/luke/lib/python3.7/site-packages/torch/serialization.py", line 555, in _load
    return legacy_load(f)
  File "/home/user/anaconda3/envs/luke/lib/python3.7/site-packages/torch/serialization.py", line 466, in legacy_load
    with closing(tarfile.open(fileobj=f, mode='r:', format=tarfile.PAX_FORMAT)) as tar, \
  File "/home/user/anaconda3/envs/luke/lib/python3.7/tarfile.py", line 1593, in open
    return func(name, filemode, fileobj, **kwargs)
  File "/home/user/anaconda3/envs/luke/lib/python3.7/tarfile.py", line 1623, in taropen
    return cls(name, mode, fileobj, **kwargs)
  File "/home/user/anaconda3/envs/luke/lib/python3.7/tarfile.py", line 1486, in __init__
    self.firstmember = self.next()
  File "/home/user/anaconda3/envs/luke/lib/python3.7/tarfile.py", line 2301, in next
    raise ReadError(str(e))
tarfile.ReadError: invalid header

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/anaconda3/envs/luke/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/user/anaconda3/envs/luke/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/user/github/luke/examples/cli.py", line 132, in <module>
    cli()
  File "/home/user/anaconda3/envs/luke/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/user/anaconda3/envs/luke/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/user/anaconda3/envs/luke/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/user/anaconda3/envs/luke/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/user/anaconda3/envs/luke/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/user/anaconda3/envs/luke/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/user/github/luke/examples/utils/trainer.py", line 32, in wrapper
    return func(*args, **kwargs)
  File "/home/user/anaconda3/envs/luke/lib/python3.7/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/home/user/github/luke/examples/relation_classification/main.py", line 110, in run
    model.load_state_dict(torch.load(args.checkpoint_file, map_location="cpu"))
  File "/home/user/anaconda3/envs/luke/lib/python3.7/site-packages/torch/serialization.py", line 386, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "/home/user/anaconda3/envs/luke/lib/python3.7/site-packages/torch/serialization.py", line 559, in _load
    raise RuntimeError("{} is a zip archive (did you mean to use torch.jit.load()?)".format(f.name))
RuntimeError: /hdd1/user/research/luke/pytorch_model.bin is a zip archive (did you mean to use torch.jit.load()?)
```

**Comment by ikuyamada** [comment]
Hi,
Did you decompress the checkpoint file? The checkpoint file is compressed using gzip, you need to decompress the file before using it.

**Comment by seanswyi** [comment]
Yes, I decompressed the file. I have a separate compressed `pytorch_model.bin.gz` underneath `pytorch_model.bin` (the one I downloaded from the Google Drive link you provided) and I'm using the decompressed one as an argument.

**Comment by ikuyamada** [comment]
Thanks for the reply. I confirmed that the checkpoint file can be loaded successfully using `torch==1.2.0`. 

```
>>> import torch
>>> m = torch.load('pytorch_model.bin')
>>> torch.__version__
'1.2.0'
```

Please confirm that torch can load the checkpoint by running the commands above.

**Comment by seanswyi** [comment]
I'm not sure why, but I kept getting the same error traceback. However, I downloaded the checkpoint and decompressed it again, and that solved the issue. Thanks for the tip!
