### ISSUE TITLE
QA task mismatch issues

### ISSUE THREAD

**Issue by XY2323819551** [studio-ousia/luke#69]
Hi, I met a problem when I run the code, do you have time to give me some suggestions? Thank you very much!

The error is as below:

Traceback (most recent call last):
  File "/data/zhangxy/condenv/torch12/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/data/zhangxy/condenv/torch12/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/data/zhangxy/LUKE/luke-master/examples/cli.py", line 132, in <module>
    cli()
  File "/data/zhangxy/condenv/torch12/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/data/zhangxy/condenv/torch12/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/data/zhangxy/condenv/torch12/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/data/zhangxy/condenv/torch12/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/data/zhangxy/condenv/torch12/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/data/zhangxy/condenv/torch12/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/data/zhangxy/LUKE/luke-master/examples/utils/trainer.py", line 32, in wrapper
    return func(*args, **kwargs)
  File "/data/zhangxy/condenv/torch12/lib/python3.6/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/data/zhangxy/LUKE/luke-master/examples/reading_comprehension/main.py", line 123, in run
    model.load_state_dict(torch.load(args.checkpoint_file, map_location="cpu"))
  File "/data/zhangxy/LUKE/luke-master/luke/model.py", line 234, in load_state_dict
    super(LukeEntityAwareAttentionModel, self).load_state_dict(new_state_dict, *args, **kwargs)
  File "/data/zhangxy/condenv/torch12/lib/python3.6/site-packages/torch/nn/modules/module.py", line 845, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for LukeForReadingComprehension:
        size mismatch for embeddings.word_embeddings.weight: copying a param with shape torch.Size([50268, 1024]) from checkpoint, the shape in current model is torch.Size([50265, 1024]).
        size mismatch for entity_embeddings.entity_embeddings.weight: copying a param with shape torch.Size([2, 256]) from checkpoint, the shape in current model is torch.Size([500000, 256]).

and I use the following command to run the code：
python -m examples.cli --model-file=./resources/luke_large_500k.tar.gz --output-dir=./output/ reading-comprehension run --data-dir=./resources/SQuAD11/ --checkpoint-file=./resources/pytorch_model.bin --no-negative --wiki-link-db-file=./resources/luke_squad_wikipedia_data/enwiki_20160305.pkl --model-redirects-file=./resources/luke_squad_wikipedia_data/enwiki_20181220_redirects.pkl --link-redirects-file=./resources/luke_squad_wikipedia_data/enwiki_20160305_redirects.pkl --no-train

I tried many times but failed, I cannot find the problem. /a little sad…

**Comment by ikuyamada** [comment]
Hi, it looks like you used the checkpoint file that was fine-tuned for tasks other than the SQuAD QA task.
Please download the file from the [corresponding link](https://drive.google.com/file/d/1097QicHAVnroVVw54niPXoY-iylGNi0K/view?usp=sharing) and try this again.

**Comment by XY2323819551** [comment]
> Hi, it looks like you used the checkpoint file that was fine-tuned for a task other than the SQuAD QA task.
> Please download the pytorch_model.bin file from the [corresponding link](https://drive.google.com/file/d/1097QicHAVnroVVw54niPXoY-iylGNi0K/view?usp=sharing) and try this again.

You are so nice, thanks for your tips, I can run it now!!
